version: '3.3'
services:
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: db_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mypassword@@aabbcc123"
      ACCEPT_EULA: "Y"
 